/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symg.symg;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.symg.symg.Attribute#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.Attribute#getAttributeType <em>Attribute Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.symg.symg.SymgPackage#getAttribute()
 * @model
 * @generated
 */
public interface Attribute extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.symg.symg.SymgPackage#getAttribute_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.symg.symg.Attribute#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Attribute Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute Type</em>' containment reference.
   * @see #setAttributeType(CType)
   * @see org.xtext.example.symg.symg.SymgPackage#getAttribute_AttributeType()
   * @model containment="true"
   * @generated
   */
  CType getAttributeType();

  /**
   * Sets the value of the '{@link org.xtext.example.symg.symg.Attribute#getAttributeType <em>Attribute Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute Type</em>' containment reference.
   * @see #getAttributeType()
   * @generated
   */
  void setAttributeType(CType value);

} // Attribute
