/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symg.symg;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>cEvent</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.symg.symg.cEvent#getContrEvent <em>Contr Event</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.cEvent#getContrName <em>Contr Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.symg.symg.SymgPackage#getcEvent()
 * @model
 * @generated
 */
public interface cEvent extends EObject
{
  /**
   * Returns the value of the '<em><b>Contr Event</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contr Event</em>' attribute.
   * @see #setContrEvent(String)
   * @see org.xtext.example.symg.symg.SymgPackage#getcEvent_ContrEvent()
   * @model
   * @generated
   */
  String getContrEvent();

  /**
   * Sets the value of the '{@link org.xtext.example.symg.symg.cEvent#getContrEvent <em>Contr Event</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contr Event</em>' attribute.
   * @see #getContrEvent()
   * @generated
   */
  void setContrEvent(String value);

  /**
   * Returns the value of the '<em><b>Contr Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contr Name</em>' attribute.
   * @see #setContrName(String)
   * @see org.xtext.example.symg.symg.SymgPackage#getcEvent_ContrName()
   * @model
   * @generated
   */
  String getContrName();

  /**
   * Sets the value of the '{@link org.xtext.example.symg.symg.cEvent#getContrName <em>Contr Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contr Name</em>' attribute.
   * @see #getContrName()
   * @generated
   */
  void setContrName(String value);

} // cEvent
