/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symg.symg;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CType</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.symg.symg.SymgPackage#getCType()
 * @model
 * @generated
 */
public interface CType extends EObject
{
} // CType
