/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symg.symg;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declar</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.symg.symg.Declar#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.Declar#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.Declar#getAttributes <em>Attributes</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.symg.symg.SymgPackage#getDeclar()
 * @model
 * @generated
 */
public interface Declar extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.symg.symg.SymgPackage#getDeclar_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.symg.symg.Declar#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(Regular)
   * @see org.xtext.example.symg.symg.SymgPackage#getDeclar_Type()
   * @model
   * @generated
   */
  Regular getType();

  /**
   * Sets the value of the '{@link org.xtext.example.symg.symg.Declar#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(Regular value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.symg.symg.DeclarPair}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see org.xtext.example.symg.symg.SymgPackage#getDeclar_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<DeclarPair> getAttributes();

} // Declar
