/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symg.symg;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Domain Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.symg.symg.DomainType#getSuperType <em>Super Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.symg.symg.SymgPackage#getDomainType()
 * @model
 * @generated
 */
public interface DomainType extends CType, TypeName
{
  /**
   * Returns the value of the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Super Type</em>' reference.
   * @see #setSuperType(DomainConcept)
   * @see org.xtext.example.symg.symg.SymgPackage#getDomainType_SuperType()
   * @model
   * @generated
   */
  DomainConcept getSuperType();

  /**
   * Sets the value of the '{@link org.xtext.example.symg.symg.DomainType#getSuperType <em>Super Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Super Type</em>' reference.
   * @see #getSuperType()
   * @generated
   */
  void setSuperType(DomainConcept value);

} // DomainType
