/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symg.symg;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.symg.symg.Model#getDomainName <em>Domain Name</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.Model#getDomainConcepts <em>Domain Concepts</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.Model#getContractName <em>Contract Name</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.Model#getParameters <em>Parameters</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.Model#getDeclarations <em>Declarations</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.Model#getPreconditions <em>Preconditions</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.Model#getPostconditions <em>Postconditions</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.Model#getObligations <em>Obligations</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.Model#getSobligations <em>Sobligations</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.Model#getPowers <em>Powers</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.Model#getConstraints <em>Constraints</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.symg.symg.SymgPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Domain Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Domain Name</em>' attribute.
   * @see #setDomainName(String)
   * @see org.xtext.example.symg.symg.SymgPackage#getModel_DomainName()
   * @model
   * @generated
   */
  String getDomainName();

  /**
   * Sets the value of the '{@link org.xtext.example.symg.symg.Model#getDomainName <em>Domain Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Domain Name</em>' attribute.
   * @see #getDomainName()
   * @generated
   */
  void setDomainName(String value);

  /**
   * Returns the value of the '<em><b>Domain Concepts</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.symg.symg.DomainConcept}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Domain Concepts</em>' containment reference list.
   * @see org.xtext.example.symg.symg.SymgPackage#getModel_DomainConcepts()
   * @model containment="true"
   * @generated
   */
  EList<DomainConcept> getDomainConcepts();

  /**
   * Returns the value of the '<em><b>Contract Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contract Name</em>' attribute.
   * @see #setContractName(String)
   * @see org.xtext.example.symg.symg.SymgPackage#getModel_ContractName()
   * @model
   * @generated
   */
  String getContractName();

  /**
   * Sets the value of the '{@link org.xtext.example.symg.symg.Model#getContractName <em>Contract Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contract Name</em>' attribute.
   * @see #getContractName()
   * @generated
   */
  void setContractName(String value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.symg.symg.Parameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see org.xtext.example.symg.symg.SymgPackage#getModel_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getParameters();

  /**
   * Returns the value of the '<em><b>Declarations</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.symg.symg.Declar}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declarations</em>' containment reference list.
   * @see org.xtext.example.symg.symg.SymgPackage#getModel_Declarations()
   * @model containment="true"
   * @generated
   */
  EList<Declar> getDeclarations();

  /**
   * Returns the value of the '<em><b>Preconditions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.symg.symg.Proposition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Preconditions</em>' containment reference list.
   * @see org.xtext.example.symg.symg.SymgPackage#getModel_Preconditions()
   * @model containment="true"
   * @generated
   */
  EList<Proposition> getPreconditions();

  /**
   * Returns the value of the '<em><b>Postconditions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.symg.symg.Proposition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Postconditions</em>' containment reference list.
   * @see org.xtext.example.symg.symg.SymgPackage#getModel_Postconditions()
   * @model containment="true"
   * @generated
   */
  EList<Proposition> getPostconditions();

  /**
   * Returns the value of the '<em><b>Obligations</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.symg.symg.Obligation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obligations</em>' containment reference list.
   * @see org.xtext.example.symg.symg.SymgPackage#getModel_Obligations()
   * @model containment="true"
   * @generated
   */
  EList<Obligation> getObligations();

  /**
   * Returns the value of the '<em><b>Sobligations</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.symg.symg.Obligation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sobligations</em>' containment reference list.
   * @see org.xtext.example.symg.symg.SymgPackage#getModel_Sobligations()
   * @model containment="true"
   * @generated
   */
  EList<Obligation> getSobligations();

  /**
   * Returns the value of the '<em><b>Powers</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.symg.symg.Power}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Powers</em>' containment reference list.
   * @see org.xtext.example.symg.symg.SymgPackage#getModel_Powers()
   * @model containment="true"
   * @generated
   */
  EList<Power> getPowers();

  /**
   * Returns the value of the '<em><b>Constraints</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.symg.symg.Proposition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraints</em>' containment reference list.
   * @see org.xtext.example.symg.symg.SymgPackage#getModel_Constraints()
   * @model containment="true"
   * @generated
   */
  EList<Proposition> getConstraints();

} // Model
