/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symg.symg;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Onto CType</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.symg.symg.OntoCType#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.symg.symg.SymgPackage#getOntoCType()
 * @model
 * @generated
 */
public interface OntoCType extends CType
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.symg.symg.SymgPackage#getOntoCType_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.symg.symg.OntoCType#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // OntoCType
