/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symg.symg;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>pState</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.symg.symg.pState#getPowState <em>Pow State</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.pState#getPowName <em>Pow Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.symg.symg.SymgPackage#getpState()
 * @model
 * @generated
 */
public interface pState extends EObject
{
  /**
   * Returns the value of the '<em><b>Pow State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pow State</em>' attribute.
   * @see #setPowState(String)
   * @see org.xtext.example.symg.symg.SymgPackage#getpState_PowState()
   * @model
   * @generated
   */
  String getPowState();

  /**
   * Sets the value of the '{@link org.xtext.example.symg.symg.pState#getPowState <em>Pow State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pow State</em>' attribute.
   * @see #getPowState()
   * @generated
   */
  void setPowState(String value);

  /**
   * Returns the value of the '<em><b>Pow Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pow Name</em>' attribute.
   * @see #setPowName(String)
   * @see org.xtext.example.symg.symg.SymgPackage#getpState_PowName()
   * @model
   * @generated
   */
  String getPowName();

  /**
   * Sets the value of the '{@link org.xtext.example.symg.symg.pState#getPowName <em>Pow Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pow Name</em>' attribute.
   * @see #getPowName()
   * @generated
   */
  void setPowName(String value);

} // pState
