/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symg.symg;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sit Prop</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.symg.symg.SitProp#getSituationName <em>Situation Name</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.SitProp#getOSituationName <em>OSituation Name</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.SitProp#getCSituationName <em>CSituation Name</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.SitProp#getPSituationName <em>PSituation Name</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.SitProp#getInterval <em>Interval</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.symg.symg.SymgPackage#getSitProp()
 * @model
 * @generated
 */
public interface SitProp extends EObject
{
  /**
   * Returns the value of the '<em><b>Situation Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Situation Name</em>' attribute.
   * @see #setSituationName(String)
   * @see org.xtext.example.symg.symg.SymgPackage#getSitProp_SituationName()
   * @model
   * @generated
   */
  String getSituationName();

  /**
   * Sets the value of the '{@link org.xtext.example.symg.symg.SitProp#getSituationName <em>Situation Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Situation Name</em>' attribute.
   * @see #getSituationName()
   * @generated
   */
  void setSituationName(String value);

  /**
   * Returns the value of the '<em><b>OSituation Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>OSituation Name</em>' containment reference.
   * @see #setOSituationName(oState)
   * @see org.xtext.example.symg.symg.SymgPackage#getSitProp_OSituationName()
   * @model containment="true"
   * @generated
   */
  oState getOSituationName();

  /**
   * Sets the value of the '{@link org.xtext.example.symg.symg.SitProp#getOSituationName <em>OSituation Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>OSituation Name</em>' containment reference.
   * @see #getOSituationName()
   * @generated
   */
  void setOSituationName(oState value);

  /**
   * Returns the value of the '<em><b>CSituation Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>CSituation Name</em>' containment reference.
   * @see #setCSituationName(cState)
   * @see org.xtext.example.symg.symg.SymgPackage#getSitProp_CSituationName()
   * @model containment="true"
   * @generated
   */
  cState getCSituationName();

  /**
   * Sets the value of the '{@link org.xtext.example.symg.symg.SitProp#getCSituationName <em>CSituation Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>CSituation Name</em>' containment reference.
   * @see #getCSituationName()
   * @generated
   */
  void setCSituationName(cState value);

  /**
   * Returns the value of the '<em><b>PSituation Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>PSituation Name</em>' containment reference.
   * @see #setPSituationName(pState)
   * @see org.xtext.example.symg.symg.SymgPackage#getSitProp_PSituationName()
   * @model containment="true"
   * @generated
   */
  pState getPSituationName();

  /**
   * Sets the value of the '{@link org.xtext.example.symg.symg.SitProp#getPSituationName <em>PSituation Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>PSituation Name</em>' containment reference.
   * @see #getPSituationName()
   * @generated
   */
  void setPSituationName(pState value);

  /**
   * Returns the value of the '<em><b>Interval</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interval</em>' containment reference.
   * @see #setInterval(Interval)
   * @see org.xtext.example.symg.symg.SymgPackage#getSitProp_Interval()
   * @model containment="true"
   * @generated
   */
  Interval getInterval();

  /**
   * Sets the value of the '{@link org.xtext.example.symg.symg.SitProp#getInterval <em>Interval</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Interval</em>' containment reference.
   * @see #getInterval()
   * @generated
   */
  void setInterval(Interval value);

} // SitProp
