/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symg.symg.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.symg.symg.SymgPackage;
import org.xtext.example.symg.symg.cEvent;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>cEvent</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.symg.symg.impl.cEventImpl#getContrEvent <em>Contr Event</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.impl.cEventImpl#getContrName <em>Contr Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class cEventImpl extends MinimalEObjectImpl.Container implements cEvent
{
  /**
   * The default value of the '{@link #getContrEvent() <em>Contr Event</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContrEvent()
   * @generated
   * @ordered
   */
  protected static final String CONTR_EVENT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getContrEvent() <em>Contr Event</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContrEvent()
   * @generated
   * @ordered
   */
  protected String contrEvent = CONTR_EVENT_EDEFAULT;

  /**
   * The default value of the '{@link #getContrName() <em>Contr Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContrName()
   * @generated
   * @ordered
   */
  protected static final String CONTR_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getContrName() <em>Contr Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContrName()
   * @generated
   * @ordered
   */
  protected String contrName = CONTR_NAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected cEventImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SymgPackage.Literals.CEVENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getContrEvent()
  {
    return contrEvent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setContrEvent(String newContrEvent)
  {
    String oldContrEvent = contrEvent;
    contrEvent = newContrEvent;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymgPackage.CEVENT__CONTR_EVENT, oldContrEvent, contrEvent));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getContrName()
  {
    return contrName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setContrName(String newContrName)
  {
    String oldContrName = contrName;
    contrName = newContrName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymgPackage.CEVENT__CONTR_NAME, oldContrName, contrName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SymgPackage.CEVENT__CONTR_EVENT:
        return getContrEvent();
      case SymgPackage.CEVENT__CONTR_NAME:
        return getContrName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SymgPackage.CEVENT__CONTR_EVENT:
        setContrEvent((String)newValue);
        return;
      case SymgPackage.CEVENT__CONTR_NAME:
        setContrName((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SymgPackage.CEVENT__CONTR_EVENT:
        setContrEvent(CONTR_EVENT_EDEFAULT);
        return;
      case SymgPackage.CEVENT__CONTR_NAME:
        setContrName(CONTR_NAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SymgPackage.CEVENT__CONTR_EVENT:
        return CONTR_EVENT_EDEFAULT == null ? contrEvent != null : !CONTR_EVENT_EDEFAULT.equals(contrEvent);
      case SymgPackage.CEVENT__CONTR_NAME:
        return CONTR_NAME_EDEFAULT == null ? contrName != null : !CONTR_NAME_EDEFAULT.equals(contrName);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (contrEvent: ");
    result.append(contrEvent);
    result.append(", contrName: ");
    result.append(contrName);
    result.append(')');
    return result.toString();
  }

} //cEventImpl
