/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symg.symg.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.symg.symg.SymgPackage;
import org.xtext.example.symg.symg.cState;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>cState</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.symg.symg.impl.cStateImpl#getContrState <em>Contr State</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.impl.cStateImpl#getContractName <em>Contract Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class cStateImpl extends MinimalEObjectImpl.Container implements cState
{
  /**
   * The default value of the '{@link #getContrState() <em>Contr State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContrState()
   * @generated
   * @ordered
   */
  protected static final String CONTR_STATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getContrState() <em>Contr State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContrState()
   * @generated
   * @ordered
   */
  protected String contrState = CONTR_STATE_EDEFAULT;

  /**
   * The default value of the '{@link #getContractName() <em>Contract Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContractName()
   * @generated
   * @ordered
   */
  protected static final String CONTRACT_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getContractName() <em>Contract Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContractName()
   * @generated
   * @ordered
   */
  protected String contractName = CONTRACT_NAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected cStateImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SymgPackage.Literals.CSTATE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getContrState()
  {
    return contrState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setContrState(String newContrState)
  {
    String oldContrState = contrState;
    contrState = newContrState;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymgPackage.CSTATE__CONTR_STATE, oldContrState, contrState));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getContractName()
  {
    return contractName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setContractName(String newContractName)
  {
    String oldContractName = contractName;
    contractName = newContractName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymgPackage.CSTATE__CONTRACT_NAME, oldContractName, contractName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SymgPackage.CSTATE__CONTR_STATE:
        return getContrState();
      case SymgPackage.CSTATE__CONTRACT_NAME:
        return getContractName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SymgPackage.CSTATE__CONTR_STATE:
        setContrState((String)newValue);
        return;
      case SymgPackage.CSTATE__CONTRACT_NAME:
        setContractName((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SymgPackage.CSTATE__CONTR_STATE:
        setContrState(CONTR_STATE_EDEFAULT);
        return;
      case SymgPackage.CSTATE__CONTRACT_NAME:
        setContractName(CONTRACT_NAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SymgPackage.CSTATE__CONTR_STATE:
        return CONTR_STATE_EDEFAULT == null ? contrState != null : !CONTR_STATE_EDEFAULT.equals(contrState);
      case SymgPackage.CSTATE__CONTRACT_NAME:
        return CONTRACT_NAME_EDEFAULT == null ? contractName != null : !CONTRACT_NAME_EDEFAULT.equals(contractName);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (contrState: ");
    result.append(contrState);
    result.append(", contractName: ");
    result.append(contractName);
    result.append(')');
    return result.toString();
  }

} //cStateImpl
