/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symg.symg.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.symg.symg.SymgPackage;
import org.xtext.example.symg.symg.pEvent;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>pEvent</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.symg.symg.impl.pEventImpl#getPowEvent <em>Pow Event</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.impl.pEventImpl#getPowName <em>Pow Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class pEventImpl extends MinimalEObjectImpl.Container implements pEvent
{
  /**
   * The default value of the '{@link #getPowEvent() <em>Pow Event</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPowEvent()
   * @generated
   * @ordered
   */
  protected static final String POW_EVENT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPowEvent() <em>Pow Event</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPowEvent()
   * @generated
   * @ordered
   */
  protected String powEvent = POW_EVENT_EDEFAULT;

  /**
   * The default value of the '{@link #getPowName() <em>Pow Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPowName()
   * @generated
   * @ordered
   */
  protected static final String POW_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPowName() <em>Pow Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPowName()
   * @generated
   * @ordered
   */
  protected String powName = POW_NAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected pEventImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SymgPackage.Literals.PEVENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPowEvent()
  {
    return powEvent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPowEvent(String newPowEvent)
  {
    String oldPowEvent = powEvent;
    powEvent = newPowEvent;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymgPackage.PEVENT__POW_EVENT, oldPowEvent, powEvent));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPowName()
  {
    return powName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPowName(String newPowName)
  {
    String oldPowName = powName;
    powName = newPowName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymgPackage.PEVENT__POW_NAME, oldPowName, powName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SymgPackage.PEVENT__POW_EVENT:
        return getPowEvent();
      case SymgPackage.PEVENT__POW_NAME:
        return getPowName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SymgPackage.PEVENT__POW_EVENT:
        setPowEvent((String)newValue);
        return;
      case SymgPackage.PEVENT__POW_NAME:
        setPowName((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SymgPackage.PEVENT__POW_EVENT:
        setPowEvent(POW_EVENT_EDEFAULT);
        return;
      case SymgPackage.PEVENT__POW_NAME:
        setPowName(POW_NAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SymgPackage.PEVENT__POW_EVENT:
        return POW_EVENT_EDEFAULT == null ? powEvent != null : !POW_EVENT_EDEFAULT.equals(powEvent);
      case SymgPackage.PEVENT__POW_NAME:
        return POW_NAME_EDEFAULT == null ? powName != null : !POW_NAME_EDEFAULT.equals(powName);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (powEvent: ");
    result.append(powEvent);
    result.append(", powName: ");
    result.append(powName);
    result.append(')');
    return result.toString();
  }

} //pEventImpl
