/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symg.symg.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.symg.symg.RelativeSituationPointBefore;
import org.xtext.example.symg.symg.SymgPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Relative Situation Point Before</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RelativeSituationPointBeforeImpl extends IntervalImpl implements RelativeSituationPointBefore
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RelativeSituationPointBeforeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SymgPackage.Literals.RELATIVE_SITUATION_POINT_BEFORE;
  }

} //RelativeSituationPointBeforeImpl
