/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symg.symg.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.symg.symg.RelativeEventPointBefore;
import org.xtext.example.symg.symg.SymgPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Relative Event Point Before</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RelativeEventPointBeforeImpl extends PointImpl implements RelativeEventPointBefore
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RelativeEventPointBeforeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SymgPackage.Literals.RELATIVE_EVENT_POINT_BEFORE;
  }

} //RelativeEventPointBeforeImpl
