/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symg.symg.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.symg.symg.Interval;
import org.xtext.example.symg.symg.SitProp;
import org.xtext.example.symg.symg.SymgPackage;
import org.xtext.example.symg.symg.cState;
import org.xtext.example.symg.symg.oState;
import org.xtext.example.symg.symg.pState;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sit Prop</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.symg.symg.impl.SitPropImpl#getSituationName <em>Situation Name</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.impl.SitPropImpl#getOSituationName <em>OSituation Name</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.impl.SitPropImpl#getCSituationName <em>CSituation Name</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.impl.SitPropImpl#getPSituationName <em>PSituation Name</em>}</li>
 *   <li>{@link org.xtext.example.symg.symg.impl.SitPropImpl#getInterval <em>Interval</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SitPropImpl extends MinimalEObjectImpl.Container implements SitProp
{
  /**
   * The default value of the '{@link #getSituationName() <em>Situation Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSituationName()
   * @generated
   * @ordered
   */
  protected static final String SITUATION_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSituationName() <em>Situation Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSituationName()
   * @generated
   * @ordered
   */
  protected String situationName = SITUATION_NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getOSituationName() <em>OSituation Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOSituationName()
   * @generated
   * @ordered
   */
  protected oState oSituationName;

  /**
   * The cached value of the '{@link #getCSituationName() <em>CSituation Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCSituationName()
   * @generated
   * @ordered
   */
  protected cState cSituationName;

  /**
   * The cached value of the '{@link #getPSituationName() <em>PSituation Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPSituationName()
   * @generated
   * @ordered
   */
  protected pState pSituationName;

  /**
   * The cached value of the '{@link #getInterval() <em>Interval</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInterval()
   * @generated
   * @ordered
   */
  protected Interval interval;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SitPropImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SymgPackage.Literals.SIT_PROP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSituationName()
  {
    return situationName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSituationName(String newSituationName)
  {
    String oldSituationName = situationName;
    situationName = newSituationName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymgPackage.SIT_PROP__SITUATION_NAME, oldSituationName, situationName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public oState getOSituationName()
  {
    return oSituationName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOSituationName(oState newOSituationName, NotificationChain msgs)
  {
    oState oldOSituationName = oSituationName;
    oSituationName = newOSituationName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SymgPackage.SIT_PROP__OSITUATION_NAME, oldOSituationName, newOSituationName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOSituationName(oState newOSituationName)
  {
    if (newOSituationName != oSituationName)
    {
      NotificationChain msgs = null;
      if (oSituationName != null)
        msgs = ((InternalEObject)oSituationName).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SymgPackage.SIT_PROP__OSITUATION_NAME, null, msgs);
      if (newOSituationName != null)
        msgs = ((InternalEObject)newOSituationName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SymgPackage.SIT_PROP__OSITUATION_NAME, null, msgs);
      msgs = basicSetOSituationName(newOSituationName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymgPackage.SIT_PROP__OSITUATION_NAME, newOSituationName, newOSituationName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public cState getCSituationName()
  {
    return cSituationName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCSituationName(cState newCSituationName, NotificationChain msgs)
  {
    cState oldCSituationName = cSituationName;
    cSituationName = newCSituationName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SymgPackage.SIT_PROP__CSITUATION_NAME, oldCSituationName, newCSituationName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCSituationName(cState newCSituationName)
  {
    if (newCSituationName != cSituationName)
    {
      NotificationChain msgs = null;
      if (cSituationName != null)
        msgs = ((InternalEObject)cSituationName).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SymgPackage.SIT_PROP__CSITUATION_NAME, null, msgs);
      if (newCSituationName != null)
        msgs = ((InternalEObject)newCSituationName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SymgPackage.SIT_PROP__CSITUATION_NAME, null, msgs);
      msgs = basicSetCSituationName(newCSituationName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymgPackage.SIT_PROP__CSITUATION_NAME, newCSituationName, newCSituationName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public pState getPSituationName()
  {
    return pSituationName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPSituationName(pState newPSituationName, NotificationChain msgs)
  {
    pState oldPSituationName = pSituationName;
    pSituationName = newPSituationName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SymgPackage.SIT_PROP__PSITUATION_NAME, oldPSituationName, newPSituationName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPSituationName(pState newPSituationName)
  {
    if (newPSituationName != pSituationName)
    {
      NotificationChain msgs = null;
      if (pSituationName != null)
        msgs = ((InternalEObject)pSituationName).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SymgPackage.SIT_PROP__PSITUATION_NAME, null, msgs);
      if (newPSituationName != null)
        msgs = ((InternalEObject)newPSituationName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SymgPackage.SIT_PROP__PSITUATION_NAME, null, msgs);
      msgs = basicSetPSituationName(newPSituationName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymgPackage.SIT_PROP__PSITUATION_NAME, newPSituationName, newPSituationName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Interval getInterval()
  {
    return interval;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInterval(Interval newInterval, NotificationChain msgs)
  {
    Interval oldInterval = interval;
    interval = newInterval;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SymgPackage.SIT_PROP__INTERVAL, oldInterval, newInterval);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInterval(Interval newInterval)
  {
    if (newInterval != interval)
    {
      NotificationChain msgs = null;
      if (interval != null)
        msgs = ((InternalEObject)interval).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SymgPackage.SIT_PROP__INTERVAL, null, msgs);
      if (newInterval != null)
        msgs = ((InternalEObject)newInterval).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SymgPackage.SIT_PROP__INTERVAL, null, msgs);
      msgs = basicSetInterval(newInterval, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymgPackage.SIT_PROP__INTERVAL, newInterval, newInterval));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SymgPackage.SIT_PROP__OSITUATION_NAME:
        return basicSetOSituationName(null, msgs);
      case SymgPackage.SIT_PROP__CSITUATION_NAME:
        return basicSetCSituationName(null, msgs);
      case SymgPackage.SIT_PROP__PSITUATION_NAME:
        return basicSetPSituationName(null, msgs);
      case SymgPackage.SIT_PROP__INTERVAL:
        return basicSetInterval(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SymgPackage.SIT_PROP__SITUATION_NAME:
        return getSituationName();
      case SymgPackage.SIT_PROP__OSITUATION_NAME:
        return getOSituationName();
      case SymgPackage.SIT_PROP__CSITUATION_NAME:
        return getCSituationName();
      case SymgPackage.SIT_PROP__PSITUATION_NAME:
        return getPSituationName();
      case SymgPackage.SIT_PROP__INTERVAL:
        return getInterval();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SymgPackage.SIT_PROP__SITUATION_NAME:
        setSituationName((String)newValue);
        return;
      case SymgPackage.SIT_PROP__OSITUATION_NAME:
        setOSituationName((oState)newValue);
        return;
      case SymgPackage.SIT_PROP__CSITUATION_NAME:
        setCSituationName((cState)newValue);
        return;
      case SymgPackage.SIT_PROP__PSITUATION_NAME:
        setPSituationName((pState)newValue);
        return;
      case SymgPackage.SIT_PROP__INTERVAL:
        setInterval((Interval)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SymgPackage.SIT_PROP__SITUATION_NAME:
        setSituationName(SITUATION_NAME_EDEFAULT);
        return;
      case SymgPackage.SIT_PROP__OSITUATION_NAME:
        setOSituationName((oState)null);
        return;
      case SymgPackage.SIT_PROP__CSITUATION_NAME:
        setCSituationName((cState)null);
        return;
      case SymgPackage.SIT_PROP__PSITUATION_NAME:
        setPSituationName((pState)null);
        return;
      case SymgPackage.SIT_PROP__INTERVAL:
        setInterval((Interval)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SymgPackage.SIT_PROP__SITUATION_NAME:
        return SITUATION_NAME_EDEFAULT == null ? situationName != null : !SITUATION_NAME_EDEFAULT.equals(situationName);
      case SymgPackage.SIT_PROP__OSITUATION_NAME:
        return oSituationName != null;
      case SymgPackage.SIT_PROP__CSITUATION_NAME:
        return cSituationName != null;
      case SymgPackage.SIT_PROP__PSITUATION_NAME:
        return pSituationName != null;
      case SymgPackage.SIT_PROP__INTERVAL:
        return interval != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (situationName: ");
    result.append(situationName);
    result.append(')');
    return result.toString();
  }

} //SitPropImpl
