/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symg.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.symg.SymgRuntimeModule;
import org.xtext.example.symg.SymgStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SymgIdeSetup extends SymgStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SymgRuntimeModule(), new SymgIdeModule()));
	}
	
}
